function oc = truth_baseline()
% 修改日志
% - v1 2026-01-21: 将“参数真源”固化到独立模块文件；运行不再依赖 opt27.m。
% - v2 2026-01-22: 5.3.3 默认敏感性点位加密（含论文点），并加入 warmStartKickStrength 以提升诊断版信息量（不改目标函数）。
% - v3 2026-02-01: 5.3.3 对齐论文口径（点位、独立求解与论文版曲线）。
% - v4 2026-02-02: 5.3.3 点位修正为论文口径 0/20/40/60/80/100。
% - v5 2026-02-02: 5.3.x 数据源改为 xlsx（论文示例静态节点数据.xlsx），与 5.4.x 统一。
% - v6 2026-02-02: useInternal 参数已废弃（内部数据机制已废除），保留仅为兼容性。
% - v7 2026-02-02: paperLineMode 改为 cummin（累积最小），确保敏感性曲线单调递减，符合论文图5.4/5.5预期。
% - v8 2026-02-03: Section532/533 配置改为从环境变量读取（由 run_modes.m 统一控制）。
%
% 说明：
% - 这些参数来自论文/opt27 口径的整理与固化，用于本工程统一 ctx 真源。
% - 禁止在 section 内部硬编码/覆写关键参数；仅允许通过 apply_override 做局部覆盖且不污染基准。

oc = struct();

% ===== EV 参数（单位明确）=====
oc.EV = struct( ...
    'B0_kWh', 100, ...
    'Bmin_kWh', 0, ...
    'Bchg_kWh', 100, ...
    'gE_kWh_per_km', 1.0, ...
    'rg_kWh_per_h', 100 ...
    );

% ===== 价格/排放（单位明确；paper_repro 严格对齐论文 5.2 节）=====
% 论文表5.1 参数来源：
%   - elec_price = 0.8 元/kWh：论文 5.2 节 "单位电量成本 we=0.8 元/kwh"
%   - fuel_price = 7.5 元/L：论文 5.2 节 "燃油价格 wL=7.5 元"
%   - carbon_price = 0.1 元/kgCO2：论文未明确给出，参考行业碳交易价格设定
%   - eCO2 = 3.09 kg/L：论文表5.1 "燃油排放因子 e=3.09 kg/L"
% ============================================
oc.Price = struct( ...
    'elec_CNY_per_kWh', 0.8, ...      % 论文 5.2 节 we=0.8
    'fuel_CNY_per_L', 7.5, ...         % 论文 5.2 节 wL=7.5
    'carbon_CNY_per_kgCO2', 0.1, ...   % 论文未明确给出，参考行业碳交易价格
    'eCO2_kg_per_L', 3.09 ...          % 论文表5.1 e=3.09
    );

% ===== 车队/速度（算法内部 Speed 为 km/min）=====
oc.Fleet = struct( ...
    'nCV', 2, ...
    'nEV', 2, ...
    'QCV', 1500, ...
    'QEV', 1000, ...
    'speed_km_per_h', 40, ...
    'speed_km_per_min', 40/60, ...
    'cCV', 100, ...
    'cEV', 200, ...
    'mCV', 20, ...
    'mEV', 10 ...
    );

% ===== CMEM（论文表5.1，CV 油耗/碳排口径）=====
oc.CMEM = struct( ...
    'mu', 44, ...
    'phi', 1, ...
    'lam', 0.2, ...
    'H', 35, ...
    'V', 5, ...
    'eta', 0.9, ...
    'eps', 0.4, ...
    'zeta', 737, ...
    'eCO2', 3.09, ...
    'rho_air', 1.225, ...
    'Cr', 0.010, ...
    'CdA', 3.0, ...
    'm_empty', 3000, ...
    'rho_fuel', 0.84 ...
    );

% ===== 模型/运行开关 =====
oc.Model = struct( ...
    'ST_min', 20, ...
    'paperModeDefault', false, ...
    'initInjectRatio', 0.0, ...
    'visual2opt', true ...
    );

% ===== 求解器参数（GA/SA）=====
oc.Solver = struct( ...
    'NP', 200, ...
    'MaxGen', 300, ...
    'Pc', 0.9, ...
    'Pm', 0.1, ...
    'Pe', 0.0, ...
    'T0', 500, ...
    'Tmin', 0.01, ...
    'alpha', 0.95, ...
    'STOP_BY_TMIN', true, ...
    'NRun', 10 ...
    );

% ===== G.opt（影响结果的算法开关）=====
oc.Gopt = struct( ...
    'paperRepairSimplify', false, ...
    'enableEliteLS', true, ...
    'eliteTopN', 8, ...
    'ls2optIter', 25, ...
    'lsOrOptTrials', 20, ...
    'crossTrials', 10, ...
    'allowWorseLS', true, ...
    'enableRelocate', true, ...
    'enableSwap', true, ...
    'heuristicRepairProb', 0.70, ...
    'strongRepairProb', 0.08, ...
    'secondRepairProb', 0.55, ...
    'initHeuristicRepairProb', 0.85, ...
    'initSecondRepairProb', 0.90, ...
    'enableImmigration', true, ...
    'immigrationPeriod', 25, ...
    'immigrationRatio', 0.05, ...
    'enableKick', true, ...
    'stagnationGen', 35, ...
    'kickProb', 0.30, ...
    'kickStrength', 3 ...
    );

% ===== CV-only 增强参数（仅在 nEV==0 场景使用）=====
oc.CVOnlyOpt = struct( ...
    'enableCVOnlyImprove', true, ...
    'enableSAFitnessAccept', true, ...
    'maxIter2optCVOnly', 2000, ...
    'cvOnlyCrossIters', 1000, ...
    'crossDetMaxEvals', 8000, ...
    'injectCount', 10, ...
    'initCapacityFix', true, ...
    'seed2optIter', 200, ...
    'lnsIters', 120, ...
    'lnsDestroyMin', 3, ...
    'lnsDestroyMax', 7, ...
    'chainIters', 120, ...
    'chainLenMin', 2, ...
    'chainLenMax', 4 ...
    );

% ===== 各 section 的默认配置 =====
% Section532 配置（优先从环境变量读取，由 run_modes.m 统一控制）
s532_custom_nCV = env_num_or_default_('SECTION532_CUSTOM_NCV', 3);
s532_custom_nEV = env_num_or_default_('SECTION532_CUSTOM_NEV', 0);
s532_custom_case_tag = env_str_or_default_('SECTION532_CUSTOM_CASE_TAG', 'CV_ONLY');
oc.Section532 = struct('custom_nCV', s532_custom_nCV, 'custom_nEV', s532_custom_nEV, 'custom_case_tag', s532_custom_case_tag);
% 5.3.3 敏感性扫描点位：论文口径 0/20/40/60/80/100（增量）
% paperIndependent：每个点独立求解（不跨点 warm-start），避免“累计最优”口径漂移
% paperLineMode：论文版曲线使用累积最小（cummin），确保单调递减符合论文图5.4/5.5预期
% warmStartKickStrength：诊断用热启动轻扰动强度（paperIndependent=true 时不启用）
% Section533 配置（优先从环境变量读取，由 run_modes.m 统一控制）
s533_incPctVec = env_vec_or_default_('SECTION533_INC_PCT_VEC', [0 20 40 60 80 100]);
s533_paperIndependent = env_bool_or_default_('SECTION533_PAPER_INDEPENDENT', true);
s533_paperLineMode = env_str_or_default_('SECTION533_PAPER_LINE_MODE', 'cummin');
s533_warmStartKick = env_num_or_default_('SECTION533_WARMSTART_KICK', 2);
oc.Section533 = struct( ...
    'incPctVec', s533_incPctVec, ...
    'paperIndependent', s533_paperIndependent, ...
    'paperLineMode', s533_paperLineMode, ...
    'warmStartKickStrength', s533_warmStartKick ...
    );

% ===== 数据开关 =====
% 注意：内部数据机制已废除（v6 2026-02-02），所有 section 强制使用 xlsx 文件
% useInternal 参数已废弃，保留仅为兼容性（不再被 get_config 使用）
oc.Data = struct('useInternal', false);

oc.Source = struct();
oc.Source.name = 'truth_baseline';
oc.Source.found = true;
oc.Source.path = mfilename('fullpath');
oc.Source.message = '固化参数真源（无需 opt27.m）';
end

% ===== 环境变量读取辅助函数（由 run_modes.m 设置）=====
function v = env_num_or_default_(name, def)
v = def;
try
    s = getenv(name);
    s = strtrim(char(string(s)));
    if ~isempty(s)
        x = str2double(s);
        if isfinite(x)
            v = x;
        end
    end
catch
    v = def;
end
end

function v = env_str_or_default_(name, def)
v = def;
try
    s = getenv(name);
    s = strtrim(char(string(s)));
    if ~isempty(s)
        v = s;
    end
catch
    v = def;
end
end

function v = env_bool_or_default_(name, def)
v = def;
try
    s = getenv(name);
    s = lower(strtrim(char(string(s))));
    if any(strcmp(s, {'1','true','on','yes'}))
        v = true;
    elseif any(strcmp(s, {'0','false','off','no'}))
        v = false;
    end
catch
    v = def;
end
end

function v = env_vec_or_default_(name, def)
v = def;
try
    s = getenv(name);
    s = strtrim(char(string(s)));
    if ~isempty(s)
        % 尝试解析 mat2str 格式的向量，如 "[0 20 40 60 80 100]"
        x = str2num(s); %#ok<ST2NM>
        if ~isempty(x) && isnumeric(x)
            v = x(:).';
        end
    end
catch
    v = def;
end
end
